from typing import Protocol, Optional

class PaymentAdapter(Protocol):
    def is_enabled(self) -> bool: ...
    def create_payment(self, *, amount: int, currency: str, customer_email: Optional[str], payment_method: Optional[str]) -> dict: ...
    def refund_payment(self, *, provider_payment_id: str, amount: int) -> dict: ...
